// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  code: __t.string().primaryKey(),
  host: __t.string(),
  maxPlayers: __t.u32().name("max_players"),
  phase: __t.string(),
  startsAt: __t.u64().name("starts_at"),
  seed: __t.u32(),
  result: __t.string(),
  createdAt: __t.u64().name("created_at"),
});
