// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  code: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  area: __t.string(),
  hp: __t.f32(),
  alarm: __t.f32(),
  spotted: __t.bool(),
  keycard: __t.bool(),
  codeFound: __t.bool(),
  vaultOpen: __t.bool(),
  alarmDisabled: __t.bool(),
  escaped: __t.bool(),
  loot: __t.u32(),
  score: __t.u32(),
  extra: __t.string(),
};
