// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const DiscoveredItem = __t.object("DiscoveredItem", {
  id: __t.string(),
  roomCode: __t.string(),
  itemId: __t.string(),
  by: __t.string(),
  at: __t.u64(),
});
export type DiscoveredItem = __Infer<typeof DiscoveredItem>;

export const GameEvent = __t.object("GameEvent", {
  id: __t.u64(),
  roomCode: __t.string(),
  tone: __t.string(),
  text: __t.string(),
  at: __t.u64(),
});
export type GameEvent = __Infer<typeof GameEvent>;

export const GameRoom = __t.object("GameRoom", {
  code: __t.string(),
  host: __t.string(),
  maxPlayers: __t.u32(),
  phase: __t.string(),
  startsAt: __t.u64(),
  seed: __t.u32(),
  result: __t.string(),
  createdAt: __t.u64(),
});
export type GameRoom = __Infer<typeof GameRoom>;

export const Player = __t.object("Player", {
  id: __t.string(),
  roomCode: __t.string(),
  identity: __t.string(),
  name: __t.string(),
  role: __t.string(),
  watching: __t.string(),
  joinedAt: __t.u64(),
});
export type Player = __Infer<typeof Player>;

export const ThiefState = __t.object("ThiefState", {
  roomCode: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  z: __t.f32(),
  yaw: __t.f32(),
  area: __t.string(),
  hp: __t.f32(),
  alarm: __t.f32(),
  spotted: __t.bool(),
  keycard: __t.bool(),
  codeFound: __t.bool(),
  vaultOpen: __t.bool(),
  alarmDisabled: __t.bool(),
  escaped: __t.bool(),
  loot: __t.u32(),
  score: __t.u32(),
  extra: __t.string(),
  updatedAt: __t.u64(),
});
export type ThiefState = __Infer<typeof ThiefState>;

