// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateRoomReducer from "../create_room_reducer";
import DiscoverItemReducer from "../discover_item_reducer";
import DrawRolesReducer from "../draw_roles_reducer";
import EndRunReducer from "../end_run_reducer";
import JoinRoomReducer from "../join_room_reducer";
import LeaveRoomReducer from "../leave_room_reducer";
import LogEventReducer from "../log_event_reducer";
import PublishWorldReducer from "../publish_world_reducer";
import StartRunReducer from "../start_run_reducer";

export type CreateRoomParams = __Infer<typeof CreateRoomReducer>;
export type DiscoverItemParams = __Infer<typeof DiscoverItemReducer>;
export type DrawRolesParams = __Infer<typeof DrawRolesReducer>;
export type EndRunParams = __Infer<typeof EndRunReducer>;
export type JoinRoomParams = __Infer<typeof JoinRoomReducer>;
export type LeaveRoomParams = __Infer<typeof LeaveRoomReducer>;
export type LogEventParams = __Infer<typeof LogEventReducer>;
export type PublishWorldParams = __Infer<typeof PublishWorldReducer>;
export type StartRunParams = __Infer<typeof StartRunReducer>;

